### PR TITLE
Fix instances of prop spreading causing incorrect intersection types

### LINKED ISSUE #543: Property "type" does not exist on ActionButton
We're currently using `HTMLAttributes<HTMLButtonElement>` to type the spread button props, but we actually need to use `ButtonHTMLAttributes<HTMLButtonElement>` in order to get a few extra valid props like `type`

### LINKED ISSUE #546: SearchBox "onChange" prop type using two disparate types
The `SearchBox` component's `onChange` prop type is a union of two different types:
1. The one we've specifically defined: `(inputValue: string) => void;`
2. Spread from the HTML form event: `FormEvent<HTMLFormEvent>`

We should only be using the former.

### PR DESCRIPTION
**Pull request by Caleb-Ellis**
## Done

- Fixed instances of prop spreading causing incorrect intersection types.
- Fixed button prop typing

### QA steps

- N/A

## Fixes

Fixes #543 
Fixes #546

### CODE REVIEW

File: src/components/Card/Card.tsx [hunk 1]
```diff
@@ -26,7 +27,7 @@ export type Props = {
    * The title of the card.
    */
   title?: ReactNode;
-};
+} & Omit<HTMLProps<HTMLDivElement>, "title">;
```
Comment (Caleb-Ellis) [inline src/components/Card/Card.tsx:30]: `Card` was missing type for the prop spread

File: src/components/CheckableInput/CheckableInput.tsx [hunk 2]
```diff
@@ -16,7 +16,7 @@ export type Props = {
    * Whether the input element should display in indeterminate state.
    */
   indeterminate?: boolean;
-} & HTMLProps<HTMLInputElement>;
+} & Omit<HTMLProps<HTMLInputElement>, "type">;
```
Comment (Caleb-Ellis) [inline src/components/CheckableInput/CheckableInput.tsx:19]: Omitting `type` here otherwise `inputType` would get overwritten if you included both `type` and `inputType` props

File: src/components/ContextualMenu/ContextualMenu.tsx [hunk 3]
```diff
@@ -97,7 +97,7 @@ export type Props<L> = {
    * Whether the menu should be visible.
    */
   visible?: boolean;
-};
+} & HTMLProps<HTMLSpanElement>;
```
Comment (Caleb-Ellis) [inline src/components/ContextualMenu/ContextualMenu.tsx:100]: `ContextualMenu` was missing type for the prop spread

File: src/components/ContextualMenu/ContextualMenuDropdown/ContextualMenuDropdown.tsx [hunk 4]
```diff
@@ -34,7 +34,7 @@ export type Props<L = null> = {
   positionNode?: HTMLElement;
   setAdjustedPosition?: (position: Position) => void;
   wrapperClass?: string;
-};
+} & HTMLProps<HTMLSpanElement>;
```
Comment (Caleb-Ellis) [inline src/components/ContextualMenu/ContextualMenuDropdown/ContextualMenuDropdown.tsx:37]: `ContextualMenuDropdown` was missing type for the prop spread

File: src/components/Input/Input.tsx [hunk 5]
```diff
@@ -52,10 +52,6 @@ export type Props = {
    * Whether to focus on the input on initial render.
    */
   takeFocus?: boolean;
-  /**
-   * The type of the input element.
-   */
-  type?: InputHTMLAttributes<HTMLInputElement>["type"];
```
Comment (Caleb-Ellis) [inline src/components/Input/Input.tsx:58]: This is already included in the prop spread

File: src/components/SearchBox/SearchBox.tsx [hunk 6]
```diff
@@ -37,7 +37,7 @@ export type Props = {
    * The value of the search input when the state is externally controlled.
    */
   value?: string;
-} & HTMLProps<HTMLFormElement>;
+} & Omit<HTMLProps<HTMLFormElement>, "onChange" | "onSubmit" | "value">;
```
Comment (Caleb-Ellis) [inline src/components/SearchBox/SearchBox.tsx:40]: We might want to revisit why we're explicitly defining `onChange`, `onSubmit` and `value` in the props type definition but for now at least there isn't an irreconcilable union type

File: src/components/ContextualMenu/ContextualMenuDropdown/ContextualMenuDropdown.tsx [hunk 7]
```diff
@@ -137,7 +137,7 @@ const generateLink = <L,>(
       key={key}
       onClick={
         onClick
-          ? (evt: React.MouseEvent) => {
+          ? (evt) => {
```
Comment (Caleb-Ellis) [inline src/components/ContextualMenu/ContextualMenuDropdown/ContextualMenuDropdown.tsx:140]: This is now properly typed via `ButtonProps`

**Review by sowasred2012 — APPROVED** [review]
